language: python
python:
  - 2.7
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install astropy statsmodels scipy==1.2 supersmoother untrendy pygam  # scipy 1.3 and statsmodel 0.9 are incompatible, fix to be expected in June 2019
  - pip install scikit-learn==0.20  # later versions don't run on Python 2.7
  - pip install numba
script:
  - python setup.py install
  - python wotan/tests.py
